import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { ArrowUpRight, Bot, Clock3, RefreshCw, ShieldCheck, FileSearch } from "lucide-react"
import { Link } from "react-router-dom"
import { Header } from "@/components/layout/Header"
import { getOperationPlan } from "@/services/workbenchService"
import "./workspace.css"

const kinds: Record<string, string> = { conversation: "Conversa aberta", review: "Revisar texto", followup: "Retorno pendente", opportunity: "Novo contato", research: "Qualificar pesquisa", manual_contact: "Contato manual aprovado" }
const issues: Record<string, string> = { missing_contact: "Sem contato utilizável", missing_name: "Nome ausente", unknown_site: "Site ainda não avaliado", suppressed: "Contatos bloqueados", uncertain_delivery: "Envio precisa de conferência", duplicate_contact: "Contato compartilhado" }
export function OperacaoPage() {
  const [minutes, setMinutes] = useState(30)
  const [filters, setFilters] = useState({ city: "", niche: "", minimum: "60" })
  const query = useQuery({ queryKey: ["operation-plan", minutes, filters], queryFn: () => getOperationPlan(minutes, filters), staleTime: 30_000 })
  const data = query.data
  return <><Header /><main className="desk-page"><div className="desk-page-heading"><div><p className="desk-eyebrow">OPERAÇÃO / SESSÃO DE TRABALHO</p><h1>Seu tempo merece<br /><em>uma próxima ação clara.</em></h1><p>Respostas primeiro, depois revisão, retornos e novos candidatos.</p></div><Link to="/pesquisa" className="desk-secondary"><FileSearch size={16} /> Mesa de pesquisa</Link></div>
    <section className="desk-session-controls" aria-label="Planejar sessão"><div className="desk-section-heading"><h2>Quanto tempo você tem?</h2><div className="desk-time-options">{[15, 30, 60].map(value => <button key={value} aria-pressed={minutes === value} onClick={() => setMinutes(value)}>{value} min</button>)}</div></div><form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); setFilters({ city: String(fields.get("city") ?? ""), niche: String(fields.get("niche") ?? ""), minimum: String(fields.get("minimum") ?? "60") }) }}><label>Cidade<input name="city" maxLength={100} placeholder="Todas as cidades" /></label><label>Segmento<input name="niche" maxLength={100} placeholder="Todos os segmentos" /></label><label>Score mínimo do Maps<select name="minimum" defaultValue="60"><option value="40">40 · ampliar</option><option value="60">60 · equilibrar</option><option value="80">80 · concentrar</option></select></label><button className="desk-primary" type="submit">Aplicar filtros</button><button className="desk-secondary" type="button" disabled={query.isFetching} onClick={() => void query.refetch()} aria-label="Atualizar fila"><RefreshCw size={16} /></button></form><p className="desk-caption">Cidade e segmento filtram Maps e pesquisa. O score é heurístico e se aplica apenas a novos contatos do Maps. Instagram mantém sua própria fila.</p></section>
    {data?.demo && <p className="desk-notice" role="status">Ambiente de teste isolado. Dados e resultados fictícios; automação desativada.</p>}
    {query.isPending && <p role="status">Organizando a sessão…</p>}{query.isError && <div className="desk-notice" role="alert">{query.error.message}<button onClick={() => void query.refetch()}>Tentar novamente</button></div>}
    {data && <><div className="desk-section-heading"><h2>{data.actions.length ? `${data.actions.length} passos para esta sessão` : "Prepare sua primeira fila"}</h2><span className="desk-time-chip"><Clock3 size={12} style={{ display: "inline", marginRight: 4 }} />~{data.estimated_minutes} / {minutes} min</span></div><div className="desk-session-progress" aria-label={`${data.estimated_minutes} de ${minutes} minutos estimados`}><span style={{ width: `${data.estimated_minutes / minutes * 100}%` }} /></div><div className="desk-home-grid"><section>{data.actions.length ? <ol className="desk-session-list">{data.actions.map((action, index) => <li key={action.id}><span className="desk-session-index">{String(index + 1).padStart(2, "0")}</span><div><span className="desk-badge">{kinds[action.kind] ?? action.kind}</span><strong style={{ marginTop: 6 }}>{action.name}</strong><p>{action.reason}</p><small className="desk-caption">{[action.city, action.niche].filter(Boolean).join(" · ")}</small></div><span className="desk-time-chip">~{action.estimated_minutes} min</span><Link to={action.href} className="desk-secondary" aria-label={`Abrir ${action.name}`}><ArrowUpRight size={16} /></Link></li>)}</ol> : <div className="desk-side-card"><FileSearch size={25} /><h2 style={{ marginTop: 18 }}>Nenhuma ação elegível neste recorte</h2><p>Confira os filtros ou incorpore a pesquisa local. Falta de fila não significa falta de oportunidade.</p><Link className="desk-primary" style={{ marginTop: 20 }} to="/pesquisa">Preparar candidatos <ArrowUpRight size={15} /></Link></div>}<p className="desk-caption">{data.unselected_actions ? `${data.unselected_actions} outras ações elegíveis ficaram fora desta sessão. ` : ""}Planejamento por regras locais. Abrir uma ação não envia mensagens nem executa IA.</p></section>
    <aside className="desk-side-card" aria-label="Prontidão da operação"><p className="desk-eyebrow">CONTROLE / LIMITES</p><h2>O bot e sua operação</h2><ul className="desk-readiness"><li><Bot size={18} /><div><strong>{data.strategy.useful_campaigns} campanhas com trabalho</strong><small>{data.strategy.active_campaigns} não pausadas. Agenda estratégica {data.strategy.enabled ? `às ${data.strategy.hour} de Brasília` : "desativada"}. {data.strategy.used_today} / {data.strategy.daily_limit} chamadas hoje.</small></div></li><li><FileSearch size={18} /><div><strong>{data.research.total} candidatos pesquisados</strong><small>{data.research.due} retornos vencidos. Pesquisas não viram alvos automáticos do Maps.</small></div></li><li><ShieldCheck size={18} /><div><strong>{data.channels.live_enabled ? "Canais sujeitos às aprovações" : "Transmissão automática desativada"}</strong><small>WhatsApp: {data.channels.whatsapp ? "configurado" : "pendente"}. E-mail: {data.channels.email ? "configurado" : "pendente"}. Configuração não comprova entrega.</small></div></li></ul><Link to="/bot" className="desk-secondary" style={{ marginTop: 20 }}>Abrir bot e agenda <ArrowUpRight size={14} /></Link></aside></div>
    <details className="desk-import" style={{ marginTop: 25 }}><summary>Qualidade da base e limites do recorte</summary><p>{data.total_leads} Maps · {data.instagram_leads} Instagram · {data.research.total} pesquisa. {data.scanned} registros Maps examinados{data.limited ? `; limite ${data.scan_limit}, recorte parcial` : ""}.</p><ul>{Object.entries(issues).filter(([key]) => data.quality[key]).map(([key, label]) => <li key={key}>{data.quality[key]} · {label}</li>)}</ul><p>{data.note}</p></details></>}
  </main></>
}
