/** Catálogo de nichos para busca de leads: negócios locais que existem no
 * Google Maps e tipicamente precisam de site (ou têm site ruim). Os textos são
 * os termos de busca reais enviados ao scraper - por isso ficam no singular e
 * na forma como as pessoas procuram no Maps. */

export interface CategoriaNichos {
  categoria: string
  nichos: string[]
}

export const CATALOGO_NICHOS: CategoriaNichos[] = [
  {
    categoria: "Saúde",
    nichos: [
      "clínica odontológica",
      "clínica de fisioterapia",
      "clínica de psicologia",
      "clínica de nutrição",
      "clínica médica",
      "clínica de estética",
      "clínica de depilação a laser",
      "laboratório de análises clínicas",
      "clínica de fonoaudiologia",
      "clínica de acupuntura",
      "clínica de podologia",
      "ótica",
      "farmácia de manipulação",
      "casa de repouso",
      "clínica de vacinação",
      "consultório de quiropraxia",
    ],
  },
  {
    categoria: "Beleza e estética",
    nichos: [
      "salão de beleza",
      "barbearia",
      "estúdio de sobrancelhas",
      "extensão de cílios",
      "esmalteria",
      "nail designer",
      "estúdio de maquiagem",
      "espaço de depilação",
      "bronzeamento artificial",
      "estúdio de tatuagem",
      "body piercing",
      "spa",
      "terapias holísticas",
    ],
  },
  {
    categoria: "Alimentação",
    nichos: [
      "restaurante",
      "pizzaria",
      "hamburgueria",
      "cafeteria",
      "confeitaria",
      "doceria",
      "padaria",
      "açaiteria",
      "sorveteria",
      "churrascaria",
      "restaurante japonês",
      "marmitaria",
      "pastelaria",
      "casa de sucos",
      "empório de produtos naturais",
      "adega",
      "distribuidora de bebidas",
    ],
  },
  {
    categoria: "Fitness e bem-estar",
    nichos: [
      "academia",
      "estúdio de pilates",
      "box de crossfit",
      "estúdio de yoga",
      "personal trainer",
      "escola de natação",
      "estúdio de dança",
      "academia de artes marciais",
      "quadra de beach tennis",
      "estúdio de treinamento funcional",
    ],
  },
  {
    categoria: "Serviços profissionais",
    nichos: [
      "escritório de advocacia",
      "escritório de contabilidade",
      "imobiliária",
      "corretor de imóveis",
      "corretora de seguros",
      "escritório de arquitetura",
      "escritório de engenharia",
      "consultoria financeira",
      "despachante",
      "assessoria de investimentos",
      "empresa de topografia",
      "perito avaliador de imóveis",
      "tradutor juramentado",
    ],
  },
  {
    categoria: "Casa e reforma",
    nichos: [
      "marcenaria",
      "marmoraria",
      "vidraçaria",
      "serralheria",
      "eletricista",
      "desentupidora",
      "empresa de pintura predial",
      "gesso e drywall",
      "paisagismo",
      "jardinagem",
      "dedetizadora",
      "instalação de ar condicionado",
      "energia solar",
      "móveis planejados",
      "esquadrias de alumínio",
      "construtora",
      "empreiteira",
      "piscinas",
      "impermeabilização",
      "calhas e telhados",
      "portões automáticos",
      "segurança eletrônica",
      "chaveiro",
      "decoração de interiores",
    ],
  },
  {
    categoria: "Automotivo",
    nichos: [
      "oficina mecânica",
      "auto elétrica",
      "funilaria e pintura",
      "estética automotiva",
      "lava rápido",
      "borracharia",
      "auto peças",
      "som automotivo",
      "insulfilm e películas",
      "vidros automotivos",
      "despachante veicular",
      "autoescola",
      "locadora de veículos",
      "guincho",
      "moto peças e oficina",
    ],
  },
  {
    categoria: "Pets",
    nichos: [
      "pet shop",
      "banho e tosa",
      "clínica veterinária",
      "hotel para cachorro",
      "adestrador de cães",
      "creche para cachorro",
    ],
  },
  {
    categoria: "Educação",
    nichos: [
      "escola de idiomas",
      "escola infantil",
      "reforço escolar",
      "escola de música",
      "aulas de violão",
      "escola de informática",
      "curso profissionalizante",
      "escola de gastronomia",
      "aulas de canto",
      "robótica para crianças",
    ],
  },
  {
    categoria: "Comércio local",
    nichos: [
      "loja de roupas",
      "boutique",
      "loja de calçados",
      "joalheria",
      "relojoaria",
      "loja de móveis",
      "loja de colchões",
      "papelaria",
      "floricultura",
      "loja de presentes",
      "loja de cosméticos",
      "perfumaria",
      "loja de tecidos",
      "armarinho",
      "loja de brinquedos",
      "loja de materiais de construção",
      "loja de tintas",
      "loja de iluminação",
      "loja de produtos naturais",
      "tabacaria",
    ],
  },
  {
    categoria: "Eventos e festas",
    nichos: [
      "buffet de festas",
      "espaço para eventos",
      "fotógrafo",
      "produtora de vídeo",
      "decoração de festas",
      "aluguel de brinquedos para festas",
      "cerimonialista",
      "doces para festas",
      "aluguel de mesas e cadeiras",
      "DJ para festas",
      "banda para eventos",
    ],
  },
  {
    categoria: "Turismo e hospedagem",
    nichos: [
      "pousada",
      "hotel",
      "hostel",
      "agência de turismo",
      "casa de temporada",
      "chácara para eventos",
    ],
  },
  {
    categoria: "Tecnologia e assistência",
    nichos: [
      "assistência técnica de celular",
      "assistência técnica de informática",
      "assistência técnica de eletrodomésticos",
      "gráfica",
      "comunicação visual",
      "loja de informática",
      "conserto de videogame",
      "instalação de câmeras de segurança",
    ],
  },
  {
    categoria: "Outros serviços",
    nichos: [
      "lavanderia",
      "atelier de costura",
      "sapataria",
      "empresa de mudanças",
      "transportadora",
      "coworking",
      "lavagem de sofá",
      "organizadora de armários",
      "cuidador de idosos",
      "empresa de limpeza",
    ],
  },
]

/** Limite espelhado do backend (MAX_NICHOS_BUSCA_MAPA). */
export const LIMITE_NICHOS_POR_BUSCA = 15

// faixa dos acentos combinantes do Unicode (NFD separa "é" em "e" + acento)
const REGEX_ACENTOS_COMBINANTES = /[̀-ͯ]/g

export function normalizarParaBusca(texto: string): string {
  return texto.normalize("NFD").replace(REGEX_ACENTOS_COMBINANTES, "").toLowerCase()
}
